# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- checkout: self  # self represents the repo where the initial Pipelines YAML file was found
  clean: true  # whether to fetch clean each time
  fetchDepth: 2  # the depth of commits to ask Git to fetch
  lfs: true  # whether to download Git-LFS files
  submodules: true | recursive  # set to 'true' for a single level of submodules or 'recursive' to get submodules of submodules
  path: buildxl_Test  # path to check out source code, relative to the agent's build directory (e.g. \_work\1)
  persistCredentials: true  # set to 'true' to leave the OAuth token in the Git config after the initial fetch
   
- script: 'bin/bxl.exe /c:config.bc /disableProcessRetryOnResourceExhaustion+'